name: CodeExecutor
module: skills.code_executor.main
category: general
description:
  en: Let your Wingman write and execute Python code, html code, or shell commands based on your request.
  de: Lass deinen Wingman Python-Code, HTML-Code oder Shell-Befehle basierend auf deiner Anfrage schreiben und ausführen.
hint:
  en: Describe the task you want to accomplish using Python, HTML or shell commands, and this skill will generate and optionally execute the code or commands for you. It helps if you directly say you want the Wingman to use Python or shell commands.
  de: Beschreibe die Aufgabe, die du mit Python, HTML oder Shell-Befehlen erreichen möchtest, und dieser Skill generiert und führt den Code oder die Befehle optional aus. Es hilft, wenn du direkt sagst, dass der Wingman Python oder Shell-Befehle verwenden soll.
examples:
  - question:
      en: Write Python code to print "Hello, world!" and execute it.
      de: Schreibe Python-Code, um "Hello, world!" auszugeben und führe ihn aus.
    answer:
      en: (Generates and executes a Python script that prints "Hello, world!")
      de: (Erzeugt und führt ein Python-Skript aus, das "Hello, world!" ausgibt)
  - question:
      en: Write the code for a hello world web page and then show me the page.
      de: Schreibe den Code für eine Hallo-Welt-Webseite und zeige sie mir dann.
    answer:
      en: (Generates html code and displays it on the default browser)
      de: (Erzeugt HTML-Code und zeigt ihn im Standardbrowser an)
  - question:
      en: Find a file named wingmanai on my C drive.
      de: Finde eine Datei namens wingmanai auf meinem C-Laufwerk.
    answer:
      en: (Drafts Python code to find a file on the user's C drive and asks the user if it is ok to execute the code)
      de: (Erstellt Python-Code, um eine Datei auf deinem C-Laufwerk zu finden, und fragt dich, ob es in Ordnung ist, den Code auszuführen)
  - question:
      en: List all files and directories in the current directory using shell commands.
      de: Liste alle Dateien und Verzeichnisse im aktuellen Verzeichnis mit Shell-Befehlen auf.
    answer:
      en: (Executes shell command `dir` to list all files and directories in the current directory)
      de: (Führt den Shell-Befehl `dir` aus, um alle Dateien und Verzeichnisse im aktuellen Verzeichnis aufzulisten)
prompt: |
  You can generate Python code, HTML code, or execute shell commands based on the user's request. You can also execute the generated code or commands if the user consents.
  If the user asks you to do something and you do not have another skill to accomplish the action, determine if python code or shell commands will help.
  In drafting python code, follow these rules: 
  (1) use a lot of print statements so that you will be able to read the results of the script after you execute it,
  (2) build in code to catch common errors and misunderstandings -- for example if the user wants to search for a certain word, make your code robust enough to catch inexact matches or differences in capitalization, and
  Python code generated will typically be executed as a string inside of exec() and shell commands will be executed inside of subprocess.run()
  However, you also have the separate capability to run external python scripts and execute pip commands, like pip install, inside of the user's default virtual environment.
  If a python script will require importing any python modules or libraries, then it is your habit to ask the user about saving the script to a file and run it from the file if approved, otherwise you will encounter errors.
  If you receive an error about installed modules or libraries not being found, then it is your habit to ask the user to save the python script to a file or allow you to save the python script to a file and then execute the file from the script to try to resolve the errors.
  When executing web code like HTML or CSS, use the execute_web_code function.
custom_properties: []