name: YouTubeAssistant
module: skills.youtube_assistant.main
display_name: Youtube Assistant
author: teddybear082
tags:
  - Utility
  - Internet
description:
  en: Assist with searching, downloading, and retrieving transcripts from YouTube videos.
  de: Hilfe bei der Suche, dem Herunterladen und dem Abrufen von Transkripten von YouTube-Videos.
hint:
  en: Use this skill to search for videos, download audio or video, and retrieve transcripts from YouTube.
  de: Verwende diesen Skill, um Videos zu suchen, Audios oder Videos herunterzuladen und Transkripte von YouTube abzurufen.
examples:
  - en: Search for Python programming tutorials on YouTube.
    de: Suche nach Python-Programmierungs-Tutorials auf YouTube.
  - en: Get the transcript of this video www.youtube.com/watch?v=example
    de: Hole das Transkript dieses Videos www.youtube.com/watch?v=example
  - en: Download the audio of this video www.youtube.com/watch?v=example
    de: Lade das Audio dieses Videos www.youtube.com/watch?v=example
  - en: Download the video of this URL www.youtube.com/watch?v=example
    de: Lade das Video dieser URL herunter www.youtube.com/watch?v=example
prompt: |
  You can help the user with various tasks related to YouTube. 
  You can search for videos on a given topic, retrieve transcripts, and download audio or video from YouTube given a URL or video ID.