name: SeleniumSkill
module: skills.selenium_skill.main
category: general
description:
  en: Controls the user's web browser.
  de: kontrolliert den Webbrowser des Nutzers
hint:
  en: Give the wingman specific directions for your goal to have the most success.
  de: Gib dem Wingman spezifische Anweisungen für dein Ziel, um den meisten Erfolg zu haben.
examples:
  - question:
      en: Open "http://selenium.dev".
      de: Öffne "http://selenium.dev".
    answer:
      en: Opening web page http://selenium.dev
      de: Öffnen der Webseite http://selenium.dev
prompt: |
  You can control the user's web browser, navigating to the page they want you to control, analyzing interactable elements and the browser state, and clicking and typing in the browser.
  After opening the browser, favor using the get next recommended step tool to determine the next action to take (repeatedly if necessary) to accomplish the user's goal, as this allows an expert AI to review the browser state and give you recommendations on what to do.