name: GoogleSearch
module: skills.google_search.main
display_name: Google Web Search
author: teddybear082
tags:
  - Internet
  - Utility
description:
  en: Perform Google searches and return various results.
  de: Führe Google-Suchen durch und gib verschiedene Ergebnisse zurück.
hint:
  en: Start your queries with "Search the web for..." or "Search the internet for..."
  de: Starte deine Anfragen mit 'Suche im Web nach...' oder 'Suche im Internet nach...'.
examples:
  - en: What is Python programming?
    de: Was ist Programmierung in Python?
  - en: Latest news about AI
    de: Neueste Nachrichten über KI
prompt: |
  This skill can execute searches on Google and return results formatted for the user using perform_google_search.
  You specify the search query to execute and other options if applicable.
  
  Examples indicating that the user wants to search the internet are:

  - "Search the web for..." or "Search the internet for..."
  - "Use Google to search for..."
  - "Find more information about..."
  - "What is the latest news about..." (or any other mention of current or recent information)
  - How is the weather forecast for... (or any other mention of future information)
  - The user is asking a question that can be answered by searching the internet and is not part of your general knowledge.
